apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: odoo

resources:
- ../../base

images:
- name: odoo-app
  newName: 846898691082.dkr.ecr.eu-central-1.amazonaws.com/odoo
  newTag: bootstrap
